version: '3.9'

services:
  app:
    image: 'bitnami/symfony:1'
    restart: always
    working_dir: '/app/app'
    ports:
      - '8000:8000'
    volumes:
      - './:/app'
      - vendor:/app/app/vendor
    environment:
      - SYMFONY_PROJECT_NAME=app
      - MYSQL_HOST=mysql
      - MYSQL_PORT_NUMBER=3306
      - MYSQL_USER=root
      - MYSQL_PASSWORD=
      - MYSQL_DATABASE=my_workout
    depends_on:
      - database
      - migration
    entrypoint: ["sh", "/app/app/entrypoint.sh"]
  database:
    image: 'bitnami/mysql:5.7.38'
    restart: always
    ports:
      - '3308:3306'
    environment:
      - ALLOW_EMPTY_PASSWORD=yes
      - MYSQL_USER=root
      - MYSQL_PASSWORD=
      - MYSQL_DATABASE=my_workout
    healthcheck:
      test: ["CMD", "mysqladmin" ,"ping", "-h", "localhost"]
      timeout: 20s
      retries: 10
    volumes:
      - 'database:/database'
  migration:
    image: 'chialab/php:8.1-apache'
    volumes:
      - '.:/app'
    entrypoint: ["/bin/sh","-c"]
    working_dir: '/app/app'
    command:
      - |
        php bin/console doctrine:migration:migrate --no-interaction
        php bin/console doctrine:fixtures:load --no-interaction
    depends_on:
      database :
        condition: service_healthy
    restart: on-failure
  redis:
    image: 'redis:7.0.2'
    restart: always
    ports:
      - '6379:6379'
    volumes:
      - 'redis:/redis'
volumes:
  app:
  vendor:
  redis:
  database: