version: '3.8'

services:
  app:
    image: 'bitnami/symfony:1'
    ports:
      - '8000:8000'
    volumes:
      - './app:/app'
    environment:
      - SYMFONY_PROJECT_NAME=app
      - MYSQL_HOST=mysql
      - MYSQL_PORT_NUMBER=3306
      - MYSQL_USER=root
      - MYSQL_PASSWORD=
      - MYSQL_DATABASE=to_do_list
    depends_on:
      - database
      - migration
  database:
    image: 'bitnami/mysql:5.7.38'
    ports:
      - '3308:3306'
    environment:
      - ALLOW_EMPTY_PASSWORD=yes
      - MYSQL_USER=root
      - MYSQL_PASSWORD=
      - MYSQL_DATABASE=to_do_list
  migration:
    image: 'chialab/php:8.1-apache'
    volumes:
      - '.:/app'
    entrypoint: ["/bin/sh","-c"]
    command:
      - |
        php /app/app/bin/console doctrine:migration:migrate --no-interaction
        php /app/app/bin/console doctrine:fixtures:load --no-interaction
    depends_on:
      - database
    healthcheck:
      test: "mysql -uroot -hdatabase"
      interval : 10s
      timeout: 10s
      retries: 10
  redis:
    image: 'redis:7.0.2'
    ports:
      - '6379:6379'
    volumes:
      - 'redis:/redis'
volumes:
  app:
  redis: