version: '2'

services:
  app:
    image: 'bitnami/symfony:1'
    ports:
      - '8000:8000'
    volumes:
      - '.:/app'
    environment:
      - SYMFONY_PROJECT_NAME=app
      - MYSQL_HOST=mysql
      - MYSQL_PORT_NUMBER=3306
      - MYSQL_USER=root
      - MYSQL_PASSWORD=
      - MYSQL_DATABASE=to_do_list
    depends_on:
      - database
  database:
    image: 'bitnami/mysql:5.7.38'
    environment:
      - ALLOW_EMPTY_PASSWORD=yes
      - MYSQL_USER=root
      - MYSQL_PASSWORD=
      - MYSQL_DATABASE=to_do_list