api_platform:
    mapping:
        paths: ['%kernel.project_dir%/src/Entity']
    patch_formats:
        json: ['application/merge-patch+json']
    swagger:
        versions: [3]
    defaults:
        pagination_items_per_page: 10
        pagination_maximum_items_per_page: 20
        pagination_minimum_items_per_page: 3
        pagination_client_items_per_page: true
    collection:
        pagination:
            items_per_page_parameter_name: perPage # Default value
            items_per_page: 10
