name: Symfony

on: [push, pull_request]

jobs:
  tests:
    runs-on: ubuntu-latest

    steps:
      - uses: shivammathur/setup-php@15c43e89cdef867065b0213be354c2841860869e
        with:
          php-version: "8.0"
      - uses: actions/checkout@v2
      - name: Copy .env
        run: php -r "file_exists('.env') || copy('.env.example', '.env');"
      - name: Install Dependencies
        run: composer app/install -q --no-ansi --no-interaction --prefer-dist
      - name: phpstan
        run: app/vendor/bin/phpstan analyse
      - name: php-cs-fixer
        run: app/vendor/bin/php-cs-fixer fix --dry-run -v --diff