name: Symfony

on: [push, pull_request]

jobs:
  tests:
    runs-on: ubuntu-latest

    steps:
      - uses: shivammathur/setup-php@15c43e89cdef867065b0213be354c2841860869e
        with:
          php-version: "8.0"
      - uses: actions/checkout@v2
      - name: Copy .env
        working-directory: ./app
        run: php -r "file_exists('.env') || copy('.env.example', '.env');"
      - name: Install Dependencies
        working-directory: ./app
        run: composer install -q --no-ansi --no-interaction --prefer-dist
      - name: phpstan
        working-directory: ./app
        run: vendor/bin/phpstan analyse
      - name: php-cs-fixer
        working-directory: ./app
        run: vendor/bin/php-cs-fixer fix --dry-run -v --diff
      - name: phpunit
        working-directory: ./app
        run: |
          - ls
          - php bin/console lexik:jwt:generate-keypair
          - vendor/bin/phpunit -d memory_limit=512M